import subprocess
import random
import urllib.parse
from grid.core import utils, git_police, scraper, config, cloud

def corporate_translator(message):
    """Turns 'fixing bug' into 'Resolved critical stability issues'."""
    msg = message.lower()
    if "fix" in msg or "bug" in msg:
        return f"Resolved critical stability issues: {message}"
    if "feat" in msg or "add" in msg:
        return f"Implemented new user-facing functionality: {message}"
    if "refactor" in msg or "clean" in msg:
        return f"Optimized technical debt to improve maintainability: {message}"
    return f"Progressed on task: {message}"

def generate_pr_link(branch, message):
    """Generates a GitHub URL that pre-fills the PR Title & Body."""
    repo_url = cloud.get_git_remote() 
    if not repo_url: return None

    base_url = repo_url.replace(".git", "")
    
    title = f"Hotfix: {message}"
    description = (
        f"### 🛡️ Grid Cowboy Protocol\n"
        f"**Automated Branch:** `{branch}`\n\n"
        f"### 📝 Summary\n"
        f"{corporate_translator(message)}\n\n"
        f"> *Generated by Grid CLI*"
    )
    
    safe_title = urllib.parse.quote(title)
    safe_body = urllib.parse.quote(description)
    
    return f"{base_url}/compare/main...{branch}?expand=1&title={safe_title}&body={safe_body}"

def run(message):
    utils.print_header("INITIATING PUSH SEQUENCE")

    # 1. AUTO-STAGE
    subprocess.run(["git", "add", "."])

    # 2. SECRET SCAN
    cfg = config.load_project_config()
    banned_files = cfg.get("banned_files", []) if cfg else [".env"]
    leaks = git_police.scan_for_secrets(custom_patterns=banned_files)
    
    if leaks:
        roast = scraper.get_random_roast("secrets")
        utils.print_error(f"PUSH BLOCKED. {roast}")
        utils.print_warning(f"Restricted files detected: {leaks}")
        subprocess.run(["git", "restore", "--staged"] + leaks)
        return

    # 3. COWBOY PROTOCOL
    current_branch = git_police.get_current_branch()
    dev_name = config.get_global_identity()
    is_cowboy = False
    safe_branch = current_branch

    # Protected branches trigger Cowboy Mode
    if current_branch in ["main", "master", "dev", "production"]:
        is_cowboy = True
        roast = scraper.get_random_roast("cowboy_shame")
        utils.print_warning(f"COWBOY DETECTED. {roast}")
        
        try:
            full_roast = scraper.get_random_roast("roasts")
            slug_words = full_roast.split()[:4]
            slug = "-".join(slug_words).lower().replace(".", "").replace("!", "")
        except:
            slug = "reckless-behavior"

        clean_msg = "".join(c if c.isalnum() else "-" for c in (message or "update")[:15]).lower()
        safe_branch = f"cowboy/{dev_name}/{clean_msg}/{slug}"
        
        utils.print_header(f"Taking the wheel... Moving to {safe_branch}")
        try:
            subprocess.run(["git", "checkout", "-b", safe_branch], check=True)
            utils.print_success(f"Branch Switched.")
        except:
            utils.print_error("Emergency branching failed.")
            return

    # 4. COMMIT & PUSH
    if not message: message = "grid auto-push"
    subprocess.run(["git", "commit", "-m", message])
    
    utils.spin_action("Pushing to Origin...", 
        lambda: subprocess.run(["git", "push", "--set-upstream", "origin", safe_branch]))

    # 5. THE VERDICT (Compliment vs Boredom vs Magic Link)
    if is_cowboy:
        # User messed up -> Magic Link
        pr_link = generate_pr_link(safe_branch, message)
        if pr_link:
            print("\n" + "="*60)
            utils.print_success("⚠️  Code pushed to safety branch.")
            print(f"\n[bold white]👉 CLICK TO OPEN PR (Pre-filled):[/]\n[underline cyan]{pr_link}[/]\n")
            print("="*60 + "\n")
    else:
        # User did good -> Check for Boredom
        # 30% chance Grid gets annoyed at your perfection
        if random.random() < 0.3:
            sassy_complaint = scraper.get_random_roast("roast_immune")
            utils.print_warning(f"Code is live. {sassy_complaint}")
        else:
            compliment = scraper.get_random_roast("compliments")
            utils.print_success(f"Code is live. {compliment}")

    scraper.trigger_background_update()